version: "3.8"

services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth

  blog-service:
    build: ./services/blog-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/blog

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - blog-service

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
